-- 마이그레이션 적용 확인 (tool/check_applied.py 가 만든 파일)
-- 결과가 0행이면 모두 적용된 것. 나온 행의 '파일' 을 SQL 에디터에서 실행하면 된다.
select file as "파일", kind as "종류", name as "이름"
  from (values
  ('001_init.sql', 'table', 'schools', to_regclass('public.schools') is not null),
  ('001_init.sql', 'table', 'profiles', to_regclass('public.profiles') is not null),
  ('001_init.sql', 'table', 'school_rules', to_regclass('public.school_rules') is not null),
  ('001_init.sql', 'table', 'daily_checkins', to_regclass('public.daily_checkins') is not null),
  ('001_init.sql', 'table', 'badges', to_regclass('public.badges') is not null),
  ('001_init.sql', 'table', 'user_badges', to_regclass('public.user_badges') is not null),
  ('001_init.sql', 'table', 'announcements', to_regclass('public.announcements') is not null),
  ('005_points_system.sql', 'table', 'point_store_items', to_regclass('public.point_store_items') is not null),
  ('005_points_system.sql', 'table', 'point_transactions', to_regclass('public.point_transactions') is not null),
  ('005_points_system.sql', 'table', 'point_exchanges', to_regclass('public.point_exchanges') is not null),
  ('010_student_roster.sql', 'table', 'student_roster', to_regclass('public.student_roster') is not null),
  ('012_fcm_tokens.sql', 'table', 'device_tokens', to_regclass('public.device_tokens') is not null),
  ('013_praise.sql', 'table', 'praise', to_regclass('public.praise') is not null),
  ('016_kodr.sql', 'table', 'kodr_records', to_regclass('public.kodr_records') is not null),
  ('018_purchase_requests.sql', 'table', 'purchase_requests', to_regclass('public.purchase_requests') is not null),
  ('019_cico.sql', 'table', 'cico_enrollments', to_regclass('public.cico_enrollments') is not null),
  ('019_cico.sql', 'table', 'cico_daily', to_regclass('public.cico_daily') is not null),
  ('019_cico.sql', 'table', 'cico_scores', to_regclass('public.cico_scores') is not null),
  ('022_subscription_renewal.sql', 'table', 'renewal_events', to_regclass('public.renewal_events') is not null),
  ('025_marketing_consent.sql', 'table', 'marketing_consent', to_regclass('public.marketing_consent') is not null),
  ('030_class_vote.sql', 'table', 'vote_subjects', to_regclass('public.vote_subjects') is not null),
  ('030_class_vote.sql', 'table', 'vote_rounds', to_regclass('public.vote_rounds') is not null),
  ('030_class_vote.sql', 'table', 'class_votes', to_regclass('public.class_votes') is not null),
  ('035_teacher_growth.sql', 'table', 'teacher_point_transactions', to_regclass('public.teacher_point_transactions') is not null),
  ('035_teacher_growth.sql', 'table', 'teacher_store_items', to_regclass('public.teacher_store_items') is not null),
  ('035_teacher_growth.sql', 'table', 'teacher_exchanges', to_regclass('public.teacher_exchanges') is not null),
  ('035_teacher_growth.sql', 'table', 'teacher_classes', to_regclass('public.teacher_classes') is not null),
  ('035_teacher_growth.sql', 'table', 'class_enrollments', to_regclass('public.class_enrollments') is not null),
  ('035_teacher_growth.sql', 'table', 'quiz_attempts', to_regclass('public.quiz_attempts') is not null),
  ('037_notifications_center.sql', 'table', 'notifications', to_regclass('public.notifications') is not null),
  ('037_notifications_center.sql', 'table', 'notification_reads', to_regclass('public.notification_reads') is not null),
  ('039_school_calendar_bulk_praise.sql', 'table', 'public_holidays', to_regclass('public.public_holidays') is not null),
  ('039_school_calendar_bulk_praise.sql', 'table', 'school_closures', to_regclass('public.school_closures') is not null),
  ('040_group_rewards.sql', 'table', 'group_contributions', to_regclass('public.group_contributions') is not null),
  ('044_vote_grade_schedule.sql', 'table', 'vote_blackouts', to_regclass('public.vote_blackouts') is not null),
  ('044_vote_grade_schedule.sql', 'table', 'vote_grade_settings', to_regclass('public.vote_grade_settings') is not null),
  ('045_app_release_vote_admin.sql', 'table', 'app_releases', to_regclass('public.app_releases') is not null),
  ('046_quiz_flexible_answers.sql', 'table', 'quiz_questions', to_regclass('public.quiz_questions') is not null),
  ('047_admin_suggestions_honor.sql', 'table', 'rule_suggestions', to_regclass('public.rule_suggestions') is not null),
  ('047_admin_suggestions_honor.sql', 'table', 'honor_gardener', to_regclass('public.honor_gardener') is not null),
  ('047_admin_suggestions_honor.sql', 'table', 'growth_level_seen', to_regclass('public.growth_level_seen') is not null),
  ('051_growth_school_year.sql', 'table', 'school_growth_year', to_regclass('public.school_growth_year') is not null),
  ('057_praise_mailbox.sql', 'table', 'praise_mail_templates', to_regclass('public.praise_mail_templates') is not null),
  ('057_praise_mailbox.sql', 'table', 'praise_mail', to_regclass('public.praise_mail') is not null),
  ('059_kodr_tiered_support.sql', 'table', 'support_referrals', to_regclass('public.support_referrals') is not null),
  ('059_kodr_tiered_support.sql', 'table', 'kodr_tier_alerts', to_regclass('public.kodr_tier_alerts') is not null),
  ('060_checkin_semester_compaction.sql', 'table', 'checkin_semester_summary', to_regclass('public.checkin_semester_summary') is not null),
  ('060_checkin_semester_compaction.sql', 'table', 'checkin_rule_semester_stats', to_regclass('public.checkin_rule_semester_stats') is not null),
  ('060_checkin_semester_compaction.sql', 'table', 'checkin_school_daily', to_regclass('public.checkin_school_daily') is not null),
  ('061_bottleneck_relief.sql', 'table', 'school_growth_cache', to_regclass('public.school_growth_cache') is not null),
  ('061_bottleneck_relief.sql', 'table', 'weekly_honor_cache', to_regclass('public.weekly_honor_cache') is not null),
  ('063_school_day_streak.sql', 'table', 'checkin_streaks', to_regclass('public.checkin_streaks') is not null),
  ('064_point_rules_mailbox_hours.sql', 'table', 'school_point_rules', to_regclass('public.school_point_rules') is not null),
  ('006_teacher_roles.sql', 'column', 'profiles.teacher_role', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'teacher_role')),
  ('008_teacher_code.sql', 'column', 'schools.teacher_code', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'teacher_code')),
  ('015_subscription.sql', 'column', 'schools.subscription_status', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'subscription_status')),
  ('015_subscription.sql', 'column', 'schools.subscription_expires_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'subscription_expires_at')),
  ('022_subscription_renewal.sql', 'column', 'schools.auto_renew', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'auto_renew')),
  ('022_subscription_renewal.sql', 'column', 'schools.grace_until', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'grace_until')),
  ('022_subscription_renewal.sql', 'column', 'schools.renewed_count', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'renewed_count')),
  ('022_subscription_renewal.sql', 'column', 'schools.last_renewal_stage', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'last_renewal_stage')),
  ('027_class_store.sql', 'column', 'point_store_items.emoji', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'emoji')),
  ('027_class_store.sql', 'column', 'point_store_items.grade', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'grade')),
  ('027_class_store.sql', 'column', 'point_store_items.class_num', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'class_num')),
  ('027_class_store.sql', 'column', 'point_store_items.created_by', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'created_by')),
  ('028_store_item_creator_name.sql', 'column', 'point_store_items.created_by_name', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'created_by_name')),
  ('031_vote_updates.sql', 'column', 'vote_rounds.total_weeks', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'vote_rounds' and column_name = 'total_weeks')),
  ('036_cico_first.sql', 'column', 'schools.kodr_cico_threshold', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'kodr_cico_threshold')),
  ('037_notifications_center.sql', 'column', 'schools.notified_growth_level', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'notified_growth_level')),
  ('040_group_rewards.sql', 'column', 'point_store_items.item_type', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'item_type')),
  ('040_group_rewards.sql', 'column', 'point_store_items.max_per_student', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'max_per_student')),
  ('040_group_rewards.sql', 'column', 'point_store_items.achieved_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'achieved_at')),
  ('040_group_rewards.sql', 'column', 'point_store_items.closed_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'point_store_items' and column_name = 'closed_at')),
  ('045_app_release_vote_admin.sql', 'column', 'vote_rounds.start_date', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'vote_rounds' and column_name = 'start_date')),
  ('045_app_release_vote_admin.sql', 'column', 'vote_rounds.end_date', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'vote_rounds' and column_name = 'end_date')),
  ('045_app_release_vote_admin.sql', 'column', 'vote_rounds.vote_weekdays', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'vote_rounds' and column_name = 'vote_weekdays')),
  ('051_growth_school_year.sql', 'column', 'growth_level_seen.year_start', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'growth_level_seen' and column_name = 'year_start')),
  ('055_roster_promotion.sql', 'column', 'profiles.left_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'left_at')),
  ('058_checkin_after_school.sql', 'column', 'schools.checkin_open_time', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'checkin_open_time')),
  ('059_kodr_tiered_support.sql', 'column', 'schools.kodr_window_days', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'kodr_window_days')),
  ('059_kodr_tiered_support.sql', 'column', 'schools.kodr_tier3_threshold', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'kodr_tier3_threshold')),
  ('059_kodr_tiered_support.sql', 'column', 'schools.kodr_tier3_year_threshold', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'kodr_tier3_year_threshold')),
  ('069_expo_demo_school.sql', 'column', 'schools.is_demo', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'is_demo')),
  ('001_init.sql', 'function', 'set_updated_at', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_updated_at')),
  ('003_fix_rls_recursion.sql', 'function', 'current_profile_school', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'current_profile_school')),
  ('003_fix_rls_recursion.sql', 'function', 'current_profile_role', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'current_profile_role')),
  ('003_fix_rls_recursion.sql', 'function', 'current_profile_id', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'current_profile_id')),
  ('004_update_default_rules.sql', 'function', 'seed_default_rules', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'seed_default_rules')),
  ('005_points_system.sql', 'function', 'get_user_points', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'get_user_points')),
  ('005_points_system.sql', 'function', 'fulfill_exchange', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'fulfill_exchange')),
  ('005_points_system.sql', 'function', 'cancel_exchange', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cancel_exchange')),
  ('006_teacher_roles.sql', 'function', 'is_admin_teacher', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'is_admin_teacher')),
  ('006_teacher_roles.sql', 'function', 'set_teacher_role', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_teacher_role')),
  ('009_reset_student_password.sql', 'function', 'reset_student_password', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reset_student_password')),
  ('010_student_roster.sql', 'function', 'upload_roster', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'upload_roster')),
  ('010_student_roster.sql', 'function', 'claim_roster', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'claim_roster')),
  ('011_roster_delete.sql', 'function', 'delete_roster_entry', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'delete_roster_entry')),
  ('011_roster_delete.sql', 'function', 'clear_roster', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'clear_roster')),
  ('012_fcm_tokens.sql', 'function', 'register_device_token', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'register_device_token')),
  ('013_praise.sql', 'function', 'mark_praise_read', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'mark_praise_read')),
  ('016_kodr.sql', 'function', 'kodr_monthly_summary', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'kodr_monthly_summary')),
  ('018_purchase_requests.sql', 'function', 'gen_teacher_code', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'gen_teacher_code')),
  ('018_purchase_requests.sql', 'function', 'list_purchase_requests', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'list_purchase_requests')),
  ('018_purchase_requests.sql', 'function', 'set_purchase_status', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_purchase_status')),
  ('018_purchase_requests.sql', 'function', 'approve_purchase_request', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'approve_purchase_request')),
  ('019_cico.sql', 'function', 'cico_start', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cico_start')),
  ('019_cico.sql', 'function', 'cico_save_day', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cico_save_day')),
  ('019_cico.sql', 'function', 'cico_student_note', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cico_student_note')),
  ('019_cico.sql', 'function', 'cico_set_status', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cico_set_status')),
  ('020_security_hardening.sql', 'function', 'verify_roster_pin', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'verify_roster_pin')),
  ('021_teacher_code_protect.sql', 'function', 'gen_unique_school_code', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'gen_unique_school_code')),
  ('021_teacher_code_protect.sql', 'function', 'find_school_by_student_code', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'find_school_by_student_code')),
  ('021_teacher_code_protect.sql', 'function', 'find_school_by_teacher_code', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'find_school_by_teacher_code')),
  ('021_teacher_code_protect.sql', 'function', 'check_duplicate_school', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'check_duplicate_school')),
  ('022_subscription_renewal.sql', 'function', 'renew_subscription', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'renew_subscription')),
  ('022_subscription_renewal.sql', 'function', 'set_auto_renew', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_auto_renew')),
  ('022_subscription_renewal.sql', 'function', 'school_annual_report', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'school_annual_report')),
  ('023_subscription_admin.sql', 'function', 'list_subscriptions', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'list_subscriptions')),
  ('024_renewal_batch.sql', 'function', 'mark_renewal_stage', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'mark_renewal_stage')),
  ('025_marketing_consent.sql', 'function', 'set_marketing_consent', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_marketing_consent')),
  ('025_marketing_consent.sql', 'function', 'get_my_marketing_consent', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'get_my_marketing_consent')),
  ('025_marketing_consent.sql', 'function', 'unsubscribe_marketing', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'unsubscribe_marketing')),
  ('025_marketing_consent.sql', 'function', 'marketing_recipients', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'marketing_recipients')),
  ('025_marketing_consent.sql', 'function', 'submit_purchase_request', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'submit_purchase_request')),
  ('026_weekly_report.sql', 'function', 'weekly_report_batch', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'weekly_report_batch')),
  ('029_find_account.sql', 'function', 'get_student_email', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'get_student_email')),
  ('030_class_vote.sql', 'function', 'kst_week_key', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'kst_week_key')),
  ('031_vote_updates.sql', 'function', 'check_class_rules_before_round', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'check_class_rules_before_round')),
  ('035_teacher_growth.sql', 'function', 'award_teacher_points', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'award_teacher_points')),
  ('035_teacher_growth.sql', 'function', 'teacher_point_balance', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'teacher_point_balance')),
  ('035_teacher_growth.sql', 'function', 'trg_award_praise', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_award_praise')),
  ('035_teacher_growth.sql', 'function', 'trg_award_vote', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_award_vote')),
  ('035_teacher_growth.sql', 'function', 'teacher_exchange_item', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'teacher_exchange_item')),
  ('035_teacher_growth.sql', 'function', 'teacher_exchange_cancel', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'teacher_exchange_cancel')),
  ('035_teacher_growth.sql', 'function', 'enroll_teacher_class', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'enroll_teacher_class')),
  ('035_teacher_growth.sql', 'function', 'cancel_class_enrollment', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cancel_class_enrollment')),
  ('035_teacher_growth.sql', 'function', 'cancel_teacher_class', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cancel_teacher_class')),
  ('035_teacher_growth.sql', 'function', 'quiz_keyword', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'quiz_keyword')),
  ('035_teacher_growth.sql', 'function', 'quiz_attempted_today', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'quiz_attempted_today')),
  ('036_cico_first.sql', 'function', 'trg_award_kodr', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_award_kodr')),
  ('036_cico_first.sql', 'function', 'trg_award_cico', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_award_cico')),
  ('037_notifications_center.sql', 'function', 'push_notification', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'push_notification')),
  ('037_notifications_center.sql', 'function', 'my_notifications', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_notifications')),
  ('037_notifications_center.sql', 'function', 'unread_notification_count', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'unread_notification_count')),
  ('037_notifications_center.sql', 'function', 'mark_notifications_read', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'mark_notifications_read')),
  ('037_notifications_center.sql', 'function', 'trg_notify_store_item', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_notify_store_item')),
  ('037_notifications_center.sql', 'function', 'trg_notify_rule', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_notify_rule')),
  ('037_notifications_center.sql', 'function', 'trg_notify_exchange', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_notify_exchange')),
  ('037_notifications_center.sql', 'function', 'trg_notify_teacher_exchange', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_notify_teacher_exchange')),
  ('037_notifications_center.sql', 'function', 'trg_notify_teacher_item', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_notify_teacher_item')),
  ('037_notifications_center.sql', 'function', 'notify_growth_levelup', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'notify_growth_levelup')),
  ('037_notifications_center.sql', 'function', 'close_point_season', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'close_point_season')),
  ('038_praise_teacher_name.sql', 'function', 'trg_notify_praise', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_notify_praise')),
  ('038_praise_teacher_name.sql', 'function', 'my_praises', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_praises')),
  ('039_school_calendar_bulk_praise.sql', 'function', 'upcoming_school_days', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'upcoming_school_days')),
  ('040_group_rewards.sql', 'function', 'request_exchange', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'request_exchange')),
  ('040_group_rewards.sql', 'function', 'contribute_to_group_item', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'contribute_to_group_item')),
  ('040_group_rewards.sql', 'function', 'group_item_status', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'group_item_status')),
  ('040_group_rewards.sql', 'function', 'fulfill_group_item', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'fulfill_group_item')),
  ('040_group_rewards.sql', 'function', 'cancel_group_item', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cancel_group_item')),
  ('041_class_point_economy.sql', 'function', 'point_economy_stats', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'point_economy_stats')),
  ('041_class_point_economy.sql', 'function', 'class_point_economy_stats', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'class_point_economy_stats')),
  ('043_homeroom.sql', 'function', 'set_my_homeroom', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_my_homeroom')),
  ('044_vote_grade_schedule.sql', 'function', 'vote_tally', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'vote_tally')),
  ('044_vote_grade_schedule.sql', 'function', 'vote_hint', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'vote_hint')),
  ('044_vote_grade_schedule.sql', 'function', 'school_grades', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'school_grades')),
  ('044_vote_grade_schedule.sql', 'function', 'vote_blackout_label', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'vote_blackout_label')),
  ('044_vote_grade_schedule.sql', 'function', 'set_vote_grade_weeks', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_vote_grade_weeks')),
  ('044_vote_grade_schedule.sql', 'function', 'set_vote_grade_close', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_vote_grade_close')),
  ('044_vote_grade_schedule.sql', 'function', 'vote_reminder_grades', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'vote_reminder_grades')),
  ('045_app_release_vote_admin.sql', 'function', 'cast_class_vote', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cast_class_vote')),
  ('045_app_release_vote_admin.sql', 'function', 'vote_grade_week', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'vote_grade_week')),
  ('045_app_release_vote_admin.sql', 'function', 'vote_round_progress', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'vote_round_progress')),
  ('045_app_release_vote_admin.sql', 'function', 'version_num', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'version_num')),
  ('045_app_release_vote_admin.sql', 'function', 'app_update_check', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'app_update_check')),
  ('045_app_release_vote_admin.sql', 'function', 'vote_today_status', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'vote_today_status')),
  ('045_app_release_vote_admin.sql', 'function', 'update_vote_round', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'update_vote_round')),
  ('045_app_release_vote_admin.sql', 'function', 'delete_vote_round', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'delete_vote_round')),
  ('045_app_release_vote_admin.sql', 'function', 'send_vote_notice', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'send_vote_notice')),
  ('046_quiz_flexible_answers.sql', 'function', 'quiz_norm', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'quiz_norm')),
  ('046_quiz_flexible_answers.sql', 'function', 'quiz_stem', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'quiz_stem')),
  ('046_quiz_flexible_answers.sql', 'function', 'quiz_is_correct', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'quiz_is_correct')),
  ('046_quiz_flexible_answers.sql', 'function', 'quiz_chosung', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'quiz_chosung')),
  ('046_quiz_flexible_answers.sql', 'function', 'quiz_rule_answers', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'quiz_rule_answers')),
  ('046_quiz_flexible_answers.sql', 'function', 'todays_quiz', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'todays_quiz')),
  ('047_admin_suggestions_honor.sql', 'function', 'reset_teacher_password', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reset_teacher_password')),
  ('047_admin_suggestions_honor.sql', 'function', 'submit_rule_suggestion', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'submit_rule_suggestion')),
  ('047_admin_suggestions_honor.sql', 'function', 'rule_suggestion_list', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'rule_suggestion_list')),
  ('047_admin_suggestions_honor.sql', 'function', 'rule_compliance_stats', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'rule_compliance_stats')),
  ('047_admin_suggestions_honor.sql', 'function', 'honor_cycle_start', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'honor_cycle_start')),
  ('047_admin_suggestions_honor.sql', 'function', 'honor_gardener_status', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'honor_gardener_status')),
  ('048_checkin_server_authority.sql', 'function', 'suspicious_checkins', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'suspicious_checkins')),
  ('049_force_latest_version.sql', 'function', 'set_version_gate', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_version_gate')),
  ('051_growth_school_year.sql', 'function', 'growth_year_start', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'growth_year_start')),
  ('051_growth_school_year.sql', 'function', 'growth_year_label', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'growth_year_label')),
  ('051_growth_school_year.sql', 'function', 'check_growth_level', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'check_growth_level')),
  ('053_checkin_points_compat.sql', 'function', 'award_checkin_points', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'award_checkin_points')),
  ('053_checkin_points_compat.sql', 'function', 'backfill_checkin_points', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'backfill_checkin_points')),
  ('053_checkin_points_compat.sql', 'function', 'backfill_missing_checkin_points', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'backfill_missing_checkin_points')),
  ('054_praise_sent_notice.sql', 'function', 'my_sent_praises', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_sent_praises')),
  ('054_praise_sent_notice.sql', 'function', 'my_praise_today', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_praise_today')),
  ('055_roster_promotion.sql', 'function', 'roster_name_key', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'roster_name_key')),
  ('055_roster_promotion.sql', 'function', 'promote_roster_plan', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'promote_roster_plan')),
  ('055_roster_promotion.sql', 'function', 'promote_roster_preview', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'promote_roster_preview')),
  ('055_roster_promotion.sql', 'function', 'promote_roster_apply', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'promote_roster_apply')),
  ('055_roster_promotion.sql', 'function', 'set_student_class', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_student_class')),
  ('055_roster_promotion.sql', 'function', 'undo_student_leave', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'undo_student_leave')),
  ('056_weekly_honor_gardener.sql', 'function', 'mask_name', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'mask_name')),
  ('057_praise_mailbox.sql', 'function', 'praise_mail_week', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'praise_mail_week')),
  ('057_praise_mailbox.sql', 'function', 'praise_mail_home', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'praise_mail_home')),
  ('057_praise_mailbox.sql', 'function', 'my_praise_mailbox', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_praise_mailbox')),
  ('057_praise_mailbox.sql', 'function', 'my_sent_praise_mail', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_sent_praise_mail')),
  ('057_praise_mailbox.sql', 'function', 'unread_praise_mail_count', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'unread_praise_mail_count')),
  ('057_praise_mailbox.sql', 'function', 'mark_praise_mail_read', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'mark_praise_mail_read')),
  ('057_praise_mailbox.sql', 'function', 'hide_praise_mail', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'hide_praise_mail')),
  ('057_praise_mailbox.sql', 'function', 'can_see_class_mail', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'can_see_class_mail')),
  ('057_praise_mailbox.sql', 'function', 'class_praise_mail', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'class_praise_mail')),
  ('057_praise_mailbox.sql', 'function', 'teacher_hide_praise_mail', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'teacher_hide_praise_mail')),
  ('058_checkin_after_school.sql', 'function', 'today_school_status', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'today_school_status')),
  ('058_checkin_after_school.sql', 'function', 'submit_checkin', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'submit_checkin')),
  ('058_checkin_after_school.sql', 'function', 'weekly_honor_rank', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'weekly_honor_rank')),
  ('058_checkin_after_school.sql', 'function', 'checkin_open_time', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'checkin_open_time')),
  ('058_checkin_after_school.sql', 'function', 'is_checkin_open', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'is_checkin_open')),
  ('058_checkin_after_school.sql', 'function', 'korean_time_label', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'korean_time_label')),
  ('059_kodr_tiered_support.sql', 'function', 'set_kodr_cico_threshold', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_kodr_cico_threshold')),
  ('059_kodr_tiered_support.sql', 'function', 'get_support_settings', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'get_support_settings')),
  ('059_kodr_tiered_support.sql', 'function', 'set_support_settings', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_support_settings')),
  ('059_kodr_tiered_support.sql', 'function', 'kodr_counts', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'kodr_counts')),
  ('059_kodr_tiered_support.sql', 'function', 'student_label', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'student_label')),
  ('059_kodr_tiered_support.sql', 'function', 'evaluate_kodr_tier', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'evaluate_kodr_tier')),
  ('059_kodr_tiered_support.sql', 'function', 'trg_kodr_tier', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_kodr_tier')),
  ('059_kodr_tiered_support.sql', 'function', 'cico_candidates', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'cico_candidates')),
  ('059_kodr_tiered_support.sql', 'function', 'support_referral_list', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'support_referral_list')),
  ('059_kodr_tiered_support.sql', 'function', 'update_support_referral', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'update_support_referral')),
  ('059_kodr_tiered_support.sql', 'function', 'create_support_referral', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'create_support_referral')),
  ('059_kodr_tiered_support.sql', 'function', 'scan_support_referrals', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'scan_support_referrals')),
  ('060_checkin_semester_compaction.sql', 'function', 'renewal_batch', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'renewal_batch')),
  ('060_checkin_semester_compaction.sql', 'function', 'semester_start', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'semester_start')),
  ('060_checkin_semester_compaction.sql', 'function', 'semester_label', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'semester_label')),
  ('060_checkin_semester_compaction.sql', 'function', 'compact_checkins', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'compact_checkins')),
  ('061_bottleneck_relief.sql', 'function', 'school_growth', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'school_growth')),
  ('061_bottleneck_relief.sql', 'function', 'weekly_honor_gardeners', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'weekly_honor_gardeners')),
  ('061_bottleneck_relief.sql', 'function', 'my_weekly_honor', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_weekly_honor')),
  ('061_bottleneck_relief.sql', 'function', 'teacher_school_overview', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'teacher_school_overview')),
  ('061_bottleneck_relief.sql', 'function', 'teacher_class_stats', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'teacher_class_stats')),
  ('061_bottleneck_relief.sql', 'function', 'my_total_checkins', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_total_checkins')),
  ('061_bottleneck_relief.sql', 'function', 'school_growth_compute', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'school_growth_compute')),
  ('061_bottleneck_relief.sql', 'function', 'weekly_honor_rank_cached', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'weekly_honor_rank_cached')),
  ('062_teacher_week_praise_stats.sql', 'function', 'school_class_list', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'school_class_list')),
  ('062_teacher_week_praise_stats.sql', 'function', 'class_week_checkins', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'class_week_checkins')),
  ('062_teacher_week_praise_stats.sql', 'function', 'praise_mail_stats', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'praise_mail_stats')),
  ('063_school_day_streak.sql', 'function', 'hall_of_fame', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'hall_of_fame')),
  ('063_school_day_streak.sql', 'function', 'student_rows', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'student_rows')),
  ('063_school_day_streak.sql', 'function', 'homeroom_overview', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'homeroom_overview')),
  ('063_school_day_streak.sql', 'function', 'prev_school_day', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'prev_school_day')),
  ('063_school_day_streak.sql', 'function', 'streak_now', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'streak_now')),
  ('063_school_day_streak.sql', 'function', 'trg_update_checkin_streak', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_update_checkin_streak')),
  ('063_school_day_streak.sql', 'function', 'my_streak', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_streak')),
  ('063_school_day_streak.sql', 'function', 'streak_leaders', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'streak_leaders')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'give_praise', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'give_praise')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'submit_quiz', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'submit_quiz')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'give_praise_bulk', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'give_praise_bulk')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'select_honor_gardener', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'select_honor_gardener')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'award_checkin_points_internal', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'award_checkin_points_internal')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'send_praise_mail', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'send_praise_mail')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'point_rule_default', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'point_rule_default')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'point_rule_range', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'point_rule_range')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'point_amount', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'point_amount')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'point_rules', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'point_rules')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'set_point_rule', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'set_point_rule')),
  ('064_point_rules_mailbox_hours.sql', 'function', 'exchange_leaders', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'exchange_leaders')),
  ('065_group_progress_for_teachers.sql', 'function', 'group_items_progress', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'group_items_progress')),
  ('066_group_contributors.sql', 'function', 'group_contributors', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'group_contributors')),
  ('067_version_gate_guard.sql', 'function', 'trg_app_releases_guard', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'trg_app_releases_guard')),
  ('067_version_gate_guard.sql', 'function', 'version_gate_status', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'version_gate_status')),
  ('068_account_cleanup.sql', 'function', 'delete_teacher', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'delete_teacher')),
  ('068_account_cleanup.sql', 'function', 'delete_student', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'delete_student')),
  ('069_expo_demo_school.sql', 'function', 'delete_my_account', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'delete_my_account')),
  ('069_expo_demo_school.sql', 'function', 'is_school_day', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'is_school_day')),
  ('069_expo_demo_school.sql', 'function', 'reset_demo_school', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reset_demo_school')),
  ('069_expo_demo_school.sql', 'function', 'setup_demo_school', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'setup_demo_school'))
  ) as t(file, kind, name, ok)
 where not ok
 order by file, kind, name;
